print("Getting Know To You!")
myName = input("What's your name?: ")
myAge = input("How old are you?: ")
food = input("What's your favourite food?: ")
music = input("What's your favourite music?: ")
home = input("Where do you live?: ")
print()
print("So you're")
print(myName)
print("and are the ripe old age of")
print(myAge)
print("you're probably hungry for")
print(food)
print("your favourite music is")
print(music)
print("So you live in the amazing!")
print(home)
